services:
  mysql:
    container_name: mysql
    platform: linux/x86_64
    build: ./sql/
    ports:
      - "3306:3306"
    volumes:
      - ./sql/db:/docker-entrypoint-initdb.d
      - ./sql/conf.d:/etc/mysql/conf.d
    env_file:
      - ./sql/local.env
    tty: true
  api:
    depends_on:
      - mysql
    container_name: fast_api
    platform: linux/x86_64
    build: ./api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    tty: true
    volumes:
      - ./api:/app
    ports:
      - 8000:8000
    env_file:
      - ./api/local.env