version: '3'
services:
  mysql:
    container_name: mysql
    platform: linux/x86_64
    build: ./docker/sql
    ports:
      - '3306:3306'
    volumes:
      - ./docker/sql/db:/docker-entrypoint-initdb.d
      - ./docker/sql/conf.d:/etc/mysql/conf.d
    env_file:
      - ./docker/sql/local.env
    tty: true

  api:
    depends_on:
      - mysql
    container_name: fast_api
    platform: linux/x86_64
    build: ./app
    restart: unless-stopped
    tty: true
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    env_file:
      - ./local.env
